const eventTypes = [
  { key: 'EARTHQUAKE', value: 'Earthquake' },
  { key: 'HURRICANE', value: 'Hurricane' },
  { key: 'TORNADO', value: 'Tornado' },
  { key: 'FLOOD', value: 'Flood' },
  { key: 'WILDFIRE', value: 'Wildfire' },
  { key: 'TSUNAMI', value: 'Tsunami' },
  { key: 'VOLCANIC_ERUPTION', value: 'Volcanic Eruption' },
  { key: 'LANDSLIDE', value: 'Landslide' },
  { key: 'DROUGHT', value: 'Drought' },
  { key: 'AVALANCHE', value: 'Avalanche' },
  { key: 'BLIZZARD', value: 'Blizzard' },
  { key: 'HEATWAVE', value: 'Heatwave' },
  { key: 'COLD_WAVE', value: 'Cold Wave' },
  { key: 'TROPICAL_STORM', value: 'Tropical Storm' },
  { key: 'STORM_SURGE', value: 'Storm Surge' },
  { key: 'HAILSTORM', value: 'Hailstorm' },
  { key: 'DUST_STORM', value: 'Dust Storm' },
  { key: 'FOG', value: 'Fog' },
  { key: 'THUNDERSTORM', value: 'Thunderstorm' },
  { key: 'SOLAR_FLARE', value: 'Solar Flare' },
  { key: 'CAR_ACCIDENT', value: 'Car Accident' },
  { key: 'PLANE_CRASH', value: 'Plane Crash' },
  { key: 'TRAIN_DERAILMENT', value: 'Train Derailment' },
  { key: 'SHIPWRECK', value: 'Shipwreck' },
  { key: 'BUILDING_COLLAPSE', value: 'Building Collapse' },
  { key: 'FIRE', value: 'Fire' },
  { key: 'EXPLOSION', value: 'Explosion' },
  { key: 'CHEMICAL_SPILL', value: 'Chemical Spill' },
  { key: 'RADIATION_LEAK', value: 'Radiation Leak' },
  { key: 'FOOD_POISONING', value: 'Food Poisoning' },
  { key: 'INDUSTRIAL_ACCIDENT', value: 'Industrial Accident' },
  { key: 'CONSTRUCTION_ACCIDENT', value: 'Construction Accident' },
  { key: 'MEDICAL_MALPRACTICE', value: 'Medical Malpractice' },
  { key: 'NATURAL_GAS_LEAK', value: 'Natural Gas Leak' },
  { key: 'POWER_OUTAGE', value: 'Power Outage' },
  { key: 'CYBERATTACK', value: 'Cyberattack' },
  { key: 'TERRORIST_ATTACK', value: 'Terrorist Attack' },
  { key: 'RIOTS', value: 'Riots' },
  { key: 'MASS_SHOOTING', value: 'Mass Shooting' },
  { key: 'DROWNING', value: 'Drowning' },
];

export { eventTypes };
